### ISSUE TITLE
Wouldn't make more sense per project configuration

### ISSUE THREAD

**Issue by lmartins** [gsingh93/sublime-quick-file-open#1]
This seems like a very useful idea, but wouldn't it be so much nicer if the files would be picked up from the current open sublime project?

**Comment by gsingh93** [comment]
Do you mean add the file that currently has focus, or do you mean something else?

**Comment by lmartins** [comment]
If im understanding correctly, this plugin will open a set of predefined files, but that set is global and not something in context with the active project. 

I was wondering if it would be possible to have file sets for each Sublime project.

**Comment by gsingh93** [comment]
Oh, I see what you're saying.

I could change the settings so that you could specify something like this:

```
project: {
    name: "my project",
    files: ["file1", "file2"]
}
```

But honestly, since I developed this plugin mainly because I wanted access to certain files regardless of the project I'm in, this feature doesn't seem very helpful to me. Especially since I can quickly open files in the specific project by hitting ctrl+p and typing the file name, but I can't do anything similar for global files. However, I will be excepting pull requests if anyone is interested.
